version: '3.9'

services:
  front:
    image: nginx
    container_name: mesatrab
    ports:
      - "80:80"
    expose:
      - 80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
